# Generated by Django 3.1.7 on 2021-08-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinformation',
            name='profession',
            field=models.CharField(default='', max_length=200),
        ),
    ]
