# Generated by Django 3.1.7 on 2021-09-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20210920_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[('Phd', 'Phd'), ('Masters', 'Masters'), ('Bachlors', 'Bachlors'), ('HSC', 'HSC'), ('SSC', 'SSC')], max_length=50),
        ),
    ]
